### ISSUE TITLE
How is KStream initialized

### ISSUE THREAD

**Issue by olaf-meyer** [redhat-developer-demos/kafka-tutorial#10]
Hello, 

I like this tutorial very much and I find it a good start to get into Kafka. In the Streams section, the consumer prints out the played songs. I don't to understand how the KStream/KTable is initialized. Could you give a hint or point me to a documentation?

Kind regards,

Olaf

**Comment by lordofthejars** [comment]
It is initialized here: https://github.com/redhat-developer-demos/kafka-tutorial/blob/master/apps/music-chart-app/quarkus/music-chart-app/src/main/java/org/acme/MusicChartTopologyProducer.java#L33

Basically I create a GlobalKTable from the songs topic.

**Comment by olaf-meyer** [comment]
Thank you very much for the response. I'm sorry, I see now that my question was ambiguous. From what I got the MusicChartTopologyProducer has one method and this method is returning a Topology. What I didn't understood at that time was that the Kafka Stream engine is initialized and started by a method that returns a Topology and the properties in the application.properties. From what I get now this is part of the quarkus kafka stream implementation.
