### ISSUE TITLE
missing 'brew install httpie'

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/kafka-tutorial#4]
brew install httpie 
is a pre-req for the Java consumer/producer section

**Comment by lordofthejars** [comment]
Ok this is something that we discussed with Kamesh, HTTPie is in the optionals section (adding now) so we expected that users might use HTTPie or if not, they will use the curl/windows thing. For this reason it is not in prerequisites section as it is something that simplifies making requests, but that's all.

**Comment by lordofthejars** [comment]
I have updated the docs.
