### ISSUE TITLE
missing create topic songs

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/kafka-tutorial#5]
The section prior has the end-user delete the song topic
https://redhat-developer-demos.github.io/kafka-tutorial/kafka-tutorial/1.0.x/05-consumes-produces.html#deletetopiccontent
but it is assumed in the next section that song topic already exists
https://redhat-developer-demos.github.io/kafka-tutorial/kafka-tutorial/1.0.x/06-java-consumer-producer.html

**Comment by lordofthejars** [comment]
No, this is to show that Kafka creates topics automatically if they are not found by default. Maybe a TIP should be added, but it is done in purpose.

**Comment by lordofthejars** [comment]
I have added the TIP
