### ISSUE TITLE
Building the Music Chart Service

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/kafka-tutorial#7]
on this page https://redhat-developer-demos.github.io/kafka-tutorial/kafka-tutorial/1.0.x/09-java-kstreams.html
cd $TUTORIAL_HOME/apps/player-app/player/song-app
and the directory structure currently looks like:
kafka-tutorial/apps/music-chart-app/quarkus/music-chart-app

**Comment by lordofthejars** [comment]
Fixed in #6
